name: Jeremy Lightsmith
email: jeremy.lightsmith@gmail.com
coaching_url: "https://calendar.app.google/QeUNxTccCZAkM5d19"
discovery_url: "https://calendar.app.google/ick9BiYhkeM3UfWb6"

sass:
  sass_dir: css
